"""create users table

Revision ID: 6f650d8fccc3
Revises: f52eb91ca168
Create Date: 2025-10-19 03:10:29.935545+09:00

# ------------------------------------------------
# DB Schema Migration
# ------------------------------------------------

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f650d8fccc3'
down_revision: Union[str, None] = 'f52eb91ca168'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
